services:
  db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: sivanajani
      POSTGRES_PASSWORD: geheim
      POSTGRES_DB: ssn_datenqualitaet
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build: ./app/backend
    container_name: backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://sivanajani:geheim@db:5432/ssn_datenqualitaet
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend