services:
  db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data 
      - ./backup:/backup
    ports:
      - "5432:5432"
  
  db_prom:
    image: postgres:15
    container_name: postgres-prom
    restart: always
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: proms_db
    volumes:
      - ./db/proms.sql:/docker-entrypoint-initdb.d/proms.sql
      - postgres-prom-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  
  
  db_meta:
    image: postgres:15
    container_name: postgres-meta
    restart: always
    environment:
      POSTGRES_USER: metaadmin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dashboard_meta
    volumes:
      - ./db/meta_init.sql:/docker-entrypoint-initdb.d/meta_init.sql
      - postgres-meta-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"


  backend:
    build: ./app/backend
    container_name: backend
    depends_on:
      - db
      - keycloak  
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PROM_DB_URL=${PROM_DB_URL} 
      - KEYCLOAK_INTERNAL_URL=http://keycloak:8080
    ports:
      - "8000:8000"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:  
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
volumes:
  postgres-data:
  pgadmin-data:
  postgres-prom-data:
  postgres-meta-data: