from sqlalchemy import Column, BigInteger, String, Text, Integer, Date, TIMESTAMP, ARRAY, Boolean
from db.session import Base


class CROMDiagnosis(Base):
    __tablename__ = "croms_diagnoses"

    id = Column(BigInteger, primary_key=True, index=True)
    tumor_anatomic_region = Column(String, nullable=True)
    tumor_anatomic_lesion_side = Column(String, nullable=True)
    tumor_syndromes = Column(ARRAY(String), nullable=True)
    tumor_diagnosis = Column(Text, nullable=True)
    additional_tumor_anatomic_region = Column(String, nullable=True)
    additional_tumor_anatomic_lesion_side = Column(String, nullable=True)
    additional_tumor_diagnosis = Column(Text, nullable=True)
    other_diagnosis = Column(Text, nullable=True)
    patient_history = Column(Text, nullable=True)
    diagnosis_ecog = Column(Integer, nullable=True)
    last_contact_date = Column(Date, nullable=True)
    last_status = Column(String, nullable=True)
    death_reason = Column(String, nullable=True)
    patient_id = Column(BigInteger, nullable=False)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)

class CROMSurgery(Base):
    __tablename__ = "croms_surgeries"

    id = Column(BigInteger, primary_key=True, index=True)
    patient_id = Column(BigInteger, nullable=False)
    surgery_date = Column(Date, nullable=False)
    institution_name = Column(String, nullable=True)
    indication = Column(String, nullable=True)
    surgery_side = Column(String, nullable=True)
    greatest_surgical_tumor_dimension_in_mm = Column(Integer, nullable=True)
    had_tumor_spillage = Column(Boolean, nullable=True)
    first_revision_details = Column(String, nullable=True)
    second_revision_details = Column(String, nullable=True)
    anatomic_region = Column(String, nullable=True)
    resection = Column(String, nullable=True)
    reconstruction = Column(String, nullable=True)
    amputation = Column(String, nullable=True)
    resected_tumor_margin = Column(String, nullable=True)
    participated_disciplines = Column(ARRAY(String), nullable=True)
    hemipelvectomy = Column(ARRAY(String), nullable=True)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)

class CROMPathology(Base):
    __tablename__ = "croms_pathologies"

    id = Column(BigInteger, primary_key=True, index=True)
    data_entry_type = Column(String, nullable=False)
    biopsy_resection_date = Column(Date, nullable=True)
    registrate_date = Column(Date, nullable=True)
    first_report_date = Column(Date, nullable=True)
    final_report_date = Column(Date, nullable=True)
    prior_pathology = Column(String, nullable=True)
    who_diagnosis = Column(String, nullable=True)
    diagnostic_grading = Column(String, nullable=True)
    judgment_of_surgical_margin = Column(String, nullable=True)
    proliferation_index = Column(String, nullable=True)
    mitoses_per_10hpf = Column(String, nullable=True)
    extent_of_necrosis = Column(String, nullable=True)
    closest_distance_to_margin_mm = Column(Integer, nullable=True)
    biological_barrier_to_closest_margin = Column(String, nullable=True)
    ihc_performed_status = Column(String, nullable=True)
    fish_performed_status = Column(String, nullable=True)
    rna_performed_status = Column(String, nullable=True)
    dna_performed_status = Column(String, nullable=True)
    ihc_result = Column(String, nullable=True)
    fish_result = Column(String, nullable=True)
    rna_result = Column(String, nullable=True)
    dna_result = Column(String, nullable=True)
    patient_id = Column(BigInteger, nullable=False)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)

class CROMRadiologyExam(Base):
    __tablename__ = "croms_radiology_exams"

    id = Column(BigInteger, primary_key=True, index=True)
    patient_id = Column(BigInteger, nullable=False)
    exam_date = Column(Date, nullable=False)
    exam_type = Column(String, nullable=True)
    imaging_timing = Column(String, nullable=True)
    imaging_type = Column(String, nullable=False)
    largest_lesion_size_in_mm = Column(Integer, nullable=True)
    medium_lesion_size_in_mm = Column(Integer, nullable=True)
    smallest_lesion_size_in_mm = Column(Integer, nullable=True)
    location_of_lesion = Column(String, nullable=True)
    recist_response = Column(String, nullable=True)
    choi_response = Column(String, nullable=True)
    irecist_response = Column(String, nullable=True)
    pet_response = Column(String, nullable=True)
    metastasis_presence = Column(Boolean, nullable=True)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)

class CROMRadiologyTherapy(Base):
    __tablename__ = "croms_radiology_therapies"

    id = Column(BigInteger, primary_key=True, index=True)
    patient_id = Column(BigInteger, nullable=False)
    indication = Column(String, nullable=True)
    therapy_type = Column(String, nullable=False)
    referral_date = Column(Date, nullable=True)
    first_contact_date = Column(Date, nullable=True)
    therapy_start_date = Column(Date, nullable=False)
    therapy_end_date = Column(Date, nullable=True)
    institution_name = Column(String, nullable=True)
    total_dose_in_gy = Column(String, nullable=True)  
    given_fractions = Column(Integer, nullable=True)
    ptv_volume_in_cm3 = Column(String, nullable=True)
    gtv_volume_in_cm3 = Column(String, nullable=True)
    was_tumor_located_in_radiated_area = Column(Boolean, nullable=True)
    was_tumor_located_with_pre_existing_lymph_edema = Column(Boolean, nullable=True)
    comments = Column(Text, nullable=True)
    hyperthermia_status = Column(String, nullable=True)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)

class CROMSarcomaBoard(Base):
    __tablename__ = "croms_sarcoma_boards"

    id = Column(BigInteger, primary_key=True, index=True)
    patient_id = Column(BigInteger, nullable=False)
    presentation_date = Column(Date, nullable=False)
    reason_for_presentation = Column(String, nullable=True)
    status_before_follow_up = Column(String, nullable=True)
    unplanned_excision_date = Column(Date, nullable=True)
    whoops_surgery_institution_name = Column(String, nullable=True)
    status_after_follow_up = Column(String, nullable=True)
    treatment_before_follow_up = Column(String, nullable=True)
    follow_up_reason = Column(String, nullable=True)
    question = Column(Text, nullable=True)
    last_execution = Column(String, nullable=True)
    proposed_procedure = Column(Text, nullable=True)
    current_ecog = Column(Integer, nullable=True)
    decision_surgery = Column(String, nullable=True)
    decision_surgery_comment = Column(Text, nullable=True)
    decision_radio_therapy = Column(String, nullable=True)
    decision_radio_therapy_comment = Column(Text, nullable=True)
    decision_systemic_surgery = Column(String, nullable=True)
    decision_systemic_surgery_comment = Column(Text, nullable=True)
    decision_follow_up = Column(String, nullable=True)
    decision_follow_up_comment = Column(Text, nullable=True)
    decision_diagnostics = Column(String, nullable=True)
    decision_diagnostics_comment = Column(Text, nullable=True)
    decision_palliative_care = Column(String, nullable=True)
    decision_palliative_care_comment = Column(Text, nullable=True)
    summary = Column(Text, nullable=True)
    further_details = Column(Text, nullable=True)
    fast_track = Column(Boolean, nullable=True, default=False)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)

class CROMSystemicTherapy(Base):
    __tablename__ = "croms_systemic_therapies"

    id = Column(BigInteger, primary_key=True, index=True)
    patient_id = Column(BigInteger, nullable=False)
    reason = Column(String, nullable=True)
    treatment_line = Column(Integer, nullable=True)
    cycles_planned = Column(String, nullable=True)
    bone_protocol = Column(String, nullable=True)
    softtissue_protocol = Column(String, nullable=True)
    institution_name = Column(String, nullable=False)
    cycle_start_date = Column(Date, nullable=True)
    cycle_end_date = Column(Date, nullable=True)
    discontinuation_reason = Column(String, nullable=True)
    was_rct_concomittant = Column(Boolean, nullable=False, default=False)
    comments = Column(Text, nullable=True)
    clinical_trial_inclusion = Column(String, nullable=True)
    hyperthermia_status = Column(String, nullable=True)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)


class CROMHyperthermiaTherapy(Base):
    __tablename__ = "croms_hyperthermia_therapies"

    id = Column(BigInteger, primary_key=True, index=True)
    indication = Column(String, nullable=True)
    start_date = Column(Date, nullable=True)
    end_date = Column(Date, nullable=True)
    hyperthermia_type = Column(String, nullable=True)
    therapy_sessions_count = Column(Integer, nullable=True)
    schedule = Column(String, nullable=True)
    board_accepted_indication = Column(Boolean, nullable=True)
    comment = Column(Text, nullable=True)
    therapy_type = Column(String, nullable=True)
    therapy_id = Column(BigInteger, nullable=True)
    patient_id = Column(BigInteger, nullable=False)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)


class CROMPatient(Base):
    __tablename__ = "croms_patients"

    id = Column(BigInteger, primary_key=True, index=True)
    external_code = Column(String, nullable=False)
    consent = Column(Boolean, nullable=False)
    ahv = Column(String, nullable=False)
    institution_name = Column(String, nullable=True)
    last_name = Column(String, nullable=False)
    first_name = Column(String, nullable=False)
    birth_date = Column(Date, nullable=True)
    gender = Column(String, nullable=False)
    street_name = Column(String, nullable=True)
    street_number = Column(String, nullable=True)
    zip_code = Column(String, nullable=True)
    city = Column(String, nullable=True)
    country = Column(String, nullable=True)
    phone_number = Column(String, nullable=True)
    email = Column(String, nullable=True)
    insurance_name = Column(String, nullable=True)
    insurance_class = Column(String, nullable=True)
    insurance_number = Column(String, nullable=True)
    general_practitioner_name = Column(String, nullable=True)
    general_practitioner_email = Column(String, nullable=True)
    created_at = Column(TIMESTAMP, nullable=False)
    updated_at = Column(TIMESTAMP, nullable=False)
